# NOTE: Please read ./README.md before using this

services:
  react:
    depends_on:
      - web
    build:
      context: ../
      target: dev
    command: sh -c 'pnpm install && pnpm start'
    volumes:
      - ../:/code
    ports:
      - 127.0.0.1:3000:3000
