name: Lint & Build

on:
  pull_request:
  push:
    branches:
      - 'develop'

env:
  APP_TITLE: ${{ vars.APP_TITLE }}
  APP_ENVIRONMENT: ${{ vars.APP_ENVIRONMENT }}
  APP_GRAPHQL_CODEGEN_ENDPOINT: ${{ vars.APP_GRAPHQL_CODEGEN_ENDPOINT }}
  APP_GRAPHQL_ENDPOINT: ${{ vars.APP_GRAPHQL_ENDPOINT }}
  APP_AUTH_URL: ${{ vars.APP_AUTH_URL }}
  APP_ADMIN_URL: ${{ vars.APP_ADMIN_URL }}
  APP_UMAMI_SRC: ${{ vars.APP_UMAMI_SRC }}
  APP_UMAMI_ID: ${{ vars.APP_UMAMI_ID }}
  APP_SENTRY_DSN: ${{ vars.APP_SENTRY_DSN }}
  GITHUB_WORKFLOW: true

jobs:
  unused:
    name: Find unused things
    environment: 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run knip
        run: pnpm generate:type && pnpm lint:unused
  lint-js:
    name: Lint JS
    environment: 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint Javascript
        run: pnpm generate:type && pnpm lint:js
  css-lint:
    name: Lint CSS
    environment: 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Css Lint
        run: pnpm lint:css
  typecheck:
    name: Typecheck
    environment: 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint Javascript
        run: pnpm generate:type && pnpm typecheck
  build:
    name: Build
    environment: 'test'
    needs: [lint-js, css-lint, typecheck]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm generate:type && pnpm build
